on: [push]

jobs:
  ddns_update_job:
    runs-on: ubuntu-latest
    name: Doing test deploy to Pinata
    steps:
      - name: Ddns update
        id: ddns-update
        uses: anantaramdas/unstoppable-domain-action@master
        with:
          mnemonic: ${{ secrets.ACTION_MNEMONIC }}
          rpc: ${{ secrets.ACTION_RPC }}
          name: 'aleksandrpopov.crypto'
          contentHash: 'QmaWTzJ8qQo6jKrRRn9xqZkHE3tMbjK6b2F41dc5EaJ4UM'
          verbose: true
          dryrun: false